--------------------------------------------------------
--  文件已创建 - 星期一-十二月-16-2019   
--------------------------------------------------------

-- USER SQL
CREATE USER "JX190718" IDENTIFIED BY "JX190718"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
GRANT "CONNECT" TO "JX190718" WITH ADMIN OPTION;
GRANT "RESOURCE" TO "JX190718" WITH ADMIN OPTION;
ALTER USER "JX190718" DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES
GRANT CREATE VIEW TO "JX190718" ;
GRANT CREATE ANY VIEW TO "JX190718" WITH ADMIN OPTION;

--------------------------------------------------------
--  DDL for Sequence APPOINTMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "JX190718"."APPOINTMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 421 CACHE 10 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BUYRECORD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "JX190718"."BUYRECORD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 71 CACHE 10 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MENU_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "JX190718"."MENU_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PATIENT_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "JX190718"."PATIENT_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 59 CACHE 10 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REPORT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "JX190718"."REPORT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 10 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ROLE_MENU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "JX190718"."ROLE_MENU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 91 CACHE 10 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ROLE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "JX190718"."ROLE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 10 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SCHEDULING_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "JX190718"."SCHEDULING_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 221 CACHE 20 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STAFF_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "JX190718"."STAFF_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 10 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SUBJECT_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "JX190718"."SUBJECT_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51 CACHE 10 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table APPOINTMENT
--------------------------------------------------------

  CREATE TABLE "JX190718"."APPOINTMENT" 
   (	"APP_ID" NUMBER(6,0), 
	"PROBLEM_ID" NUMBER(6,0), 
	"SCHEDULING_ID" NUMBER(6,0), 
	"HOUR" NUMBER(6,0), 
	"PATIENT_ACCOUNT" VARCHAR2(20 BYTE), 
	"APPOINTMENT_STAGE" NVARCHAR2(20), 
	"PROBLEM" NVARCHAR2(100), 
	"ACTTIME" NVARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "JX190718"."APPOINTMENT"."SCHEDULING_ID" IS '排班表的ID';
 
   COMMENT ON COLUMN "JX190718"."APPOINTMENT"."HOUR" IS '某一个时刻';
 
   COMMENT ON COLUMN "JX190718"."APPOINTMENT"."PATIENT_ACCOUNT" IS '病人账号';
 
   COMMENT ON COLUMN "JX190718"."APPOINTMENT"."APPOINTMENT_STAGE" IS '预约状态';
 
   COMMENT ON COLUMN "JX190718"."APPOINTMENT"."PROBLEM" IS '问题描述';
 
   COMMENT ON COLUMN "JX190718"."APPOINTMENT"."ACTTIME" IS '完成时间';
 
   COMMENT ON TABLE "JX190718"."APPOINTMENT"  IS '预约时间表';
--------------------------------------------------------
--  DDL for Table BUYRECORD
--------------------------------------------------------

  CREATE TABLE "JX190718"."BUYRECORD" 
   (	"FEIFEN" CHAR(10 BYTE), 
	"ID" NUMBER(6,0), 
	"MONEYTIME" NVARCHAR2(40), 
	"MATTER" NVARCHAR2(8), 
	"KEY_PERSON" NVARCHAR2(8), 
	"TYPE" NVARCHAR2(8), 
	"MONEY" NUMBER(6,0), 
	"PATIENT_ACCOUNT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "JX190718"."BUYRECORD"."ID" IS '交易记录表的ID';
 
   COMMENT ON COLUMN "JX190718"."BUYRECORD"."MONEYTIME" IS '交易发生时间';
 
   COMMENT ON COLUMN "JX190718"."BUYRECORD"."MATTER" IS '发生事项';
 
   COMMENT ON TABLE "JX190718"."BUYRECORD"  IS '交易记录表';
--------------------------------------------------------
--  DDL for Table DIAGNOSTIC
--------------------------------------------------------

  CREATE TABLE "JX190718"."DIAGNOSTIC" 
   (	"ID" NUMBER(6,0), 
	"PROBLEM_ID" NUMBER(6,0), 
	"REPLY" NVARCHAR2(100), 
	"REPLY_TIME" NVARCHAR2(40), 
	"APPRAISE" NVARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON TABLE "JX190718"."DIAGNOSTIC"  IS '诊断记录表';
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "JX190718"."MENU" 
   (	"FEIFEN" CHAR(10 BYTE), 
	"MENU_ID" NUMBER(6,0), 
	"FARTHER_ID" NUMBER(6,0), 
	"MENU_NAME" NVARCHAR2(40), 
	"MENU_PATH" NVARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PATIENT
--------------------------------------------------------

  CREATE TABLE "JX190718"."PATIENT" 
   (	"PATIENT_ID" NUMBER(4,0), 
	"ROLE_ID" NUMBER(6,0), 
	"PATIENT_ACCOUNT" VARCHAR2(20 BYTE), 
	"PATIENT_NAME" NVARCHAR2(6), 
	"PATIENT_PWD" VARCHAR2(30 BYTE), 
	"PATIENT_SEXY" NVARCHAR2(4), 
	"PATIENT_AGE" NUMBER(10,0), 
	"PATIENT_STAGE" NVARCHAR2(4), 
	"PATIENT_REGTIME" NVARCHAR2(25), 
	"PHONE" NUMBER(12,0), 
	"PURSE" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON TABLE "JX190718"."PATIENT"  IS '病人表';
--------------------------------------------------------
--  DDL for Table REPORT_TABLE
--------------------------------------------------------

  CREATE TABLE "JX190718"."REPORT_TABLE" 
   (	"RESULT" NVARCHAR2(40), 
	"REPORT_ID" NUMBER(6,0), 
	"PATIENT_ACCOUNT" VARCHAR2(20 BYTE), 
	"REPORT_TIME" VARCHAR2(20 BYTE), 
	"SUBJECT_DOMAIN" NVARCHAR2(10), 
	"SCORE" CHAR(10 BYTE), 
	"RESULT_TEXT" NVARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "JX190718"."REPORT_TABLE"."REPORT_TIME" IS '日期';
 
   COMMENT ON TABLE "JX190718"."REPORT_TABLE"  IS '评测报告表';
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "JX190718"."ROLE" 
   (	"FEIFEN" CHAR(10 BYTE), 
	"ROLE_ID" NUMBER(6,0), 
	"ROLE_NAME" NVARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "JX190718"."ROLE"."ROLE_NAME" IS '角色名';
 
   COMMENT ON TABLE "JX190718"."ROLE"  IS '角色表';
--------------------------------------------------------
--  DDL for Table ROLE_MENU
--------------------------------------------------------

  CREATE TABLE "JX190718"."ROLE_MENU" 
   (	"FEIFEN" CHAR(10 BYTE), 
	"ID" NUMBER(6,0), 
	"ROLE_NAME" NVARCHAR2(20), 
	"MENU_ID" NUMBER(6,0), 
	"MENU_STAGE" NVARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON TABLE "JX190718"."ROLE_MENU"  IS '角色与菜单对应表';
--------------------------------------------------------
--  DDL for Table SCHEDULING
--------------------------------------------------------

  CREATE TABLE "JX190718"."SCHEDULING" 
   (	"STAFF_NAME" NVARCHAR2(20), 
	"SCHEDULING_ID" NUMBER(6,0), 
	"STAFF_ACCOUNT" VARCHAR2(20 BYTE), 
	"DATADAY" NVARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "JX190718"."SCHEDULING"."DATADAY" IS '日期';
 
   COMMENT ON TABLE "JX190718"."SCHEDULING"  IS '工作人员排班表';
--------------------------------------------------------
--  DDL for Table STAFF
--------------------------------------------------------

  CREATE TABLE "JX190718"."STAFF" 
   (	"FEIFEN" CHAR(10 BYTE), 
	"STAFF_STAGE" NUMBER(4,0), 
	"STAFF_ID" NUMBER(4,0), 
	"STAFF_ACCOUNT" VARCHAR2(20 BYTE), 
	"ROLE_ID" NUMBER(6,0), 
	"STAFF_NAME" NVARCHAR2(8), 
	"STAFF_SEXY" NVARCHAR2(4), 
	"STAFF_PWD" VARCHAR2(30 BYTE), 
	"STAFF_SCHOOL" NVARCHAR2(20), 
	"STAFF_AWARDED" NVARCHAR2(6), 
	"STAFF_DOMAIN" NVARCHAR2(10), 
	"STAFF_BACKGROUND" NCHAR(50), 
	"STAFF_RESUME" NVARCHAR2(100), 
	"COST" NUMBER(4,0), 
	"PURSE" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "JX190718"."STAFF"."STAFF_DOMAIN" IS '领域';
 
   COMMENT ON COLUMN "JX190718"."STAFF"."STAFF_BACKGROUND" IS '专业背景';
 
   COMMENT ON COLUMN "JX190718"."STAFF"."STAFF_RESUME" IS '简介';
 
   COMMENT ON COLUMN "JX190718"."STAFF"."COST" IS '费用';
 
   COMMENT ON COLUMN "JX190718"."STAFF"."PURSE" IS '钱包';
 
   COMMENT ON TABLE "JX190718"."STAFF"  IS '工作人员表';
--------------------------------------------------------
--  DDL for Table SUBJECT
--------------------------------------------------------

  CREATE TABLE "JX190718"."SUBJECT" 
   (	"FEIFEN" CHAR(10 BYTE), 
	"SUBJECT_ID" NUMBER(6,0), 
	"SUBJECT_TEXT" NVARCHAR2(100), 
	"SUBJECT_DOMAIN" NVARCHAR2(10), 
	"OPTION_A" NVARCHAR2(50), 
	"OPTION_B" NVARCHAR2(50), 
	"OPTION_C" NVARCHAR2(50), 
	"OPTION_D" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON TABLE "JX190718"."SUBJECT"  IS '题库表';
REM INSERTING into JX190718.APPOINTMENT
SET DEFINE OFF;
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,376,181,16,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,378,182,10,'123','已确认','人防污染','2019-12-12 0:40:21');
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,380,182,14,'123','已评价','213','2019-12-11 20:43:44');
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,382,182,16,'123','已终止','846868','2019-12-12 0:54:43');
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,384,183,10,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,386,183,14,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,372,181,10,'123','已诊断','24112','2019-12-12 0:40:06');
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,374,181,14,'123','已终止','5123231','2019-12-12 0:28:33');
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,388,183,16,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,375,181,15,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,377,182,9,'123','已确认','4364','2019-12-12 0:54:39');
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,379,182,11,'123','已确认','876786','2019-12-12 0:54:41');
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,371,181,9,'123','已终止','12312','2019-12-12 0:28:17');
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,373,181,11,'123','已诊断','123','2019-12-12 0:40:00');
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,381,182,15,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,383,183,9,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,385,183,11,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,387,183,15,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,391,201,9,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,393,201,11,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,395,201,15,'123','已预约','1234',null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,398,202,10,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,400,202,14,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,402,202,16,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,403,203,9,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,405,203,11,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,407,203,15,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,410,204,10,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,412,204,14,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,414,204,16,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,392,201,10,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,396,201,16,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,397,202,9,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,399,202,11,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,394,201,14,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,401,202,15,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,404,203,10,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,406,203,14,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,408,203,16,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,409,204,9,null,'未预约',null,null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,411,204,11,'123','已预约','qwewqe',null);
Insert into JX190718.APPOINTMENT (APP_ID,PROBLEM_ID,SCHEDULING_ID,HOUR,PATIENT_ACCOUNT,APPOINTMENT_STAGE,PROBLEM,ACTTIME) values (null,413,204,15,null,'未预约',null,null);
REM INSERTING into JX190718.BUYRECORD
SET DEFINE OFF;
Insert into JX190718.BUYRECORD (FEIFEN,ID,MONEYTIME,MATTER,KEY_PERSON,TYPE,MONEY,PATIENT_ACCOUNT) values (null,31,'2019-12-11 20:42:59',' 咨询支出','条否','支出',100,'123');
Insert into JX190718.BUYRECORD (FEIFEN,ID,MONEYTIME,MATTER,KEY_PERSON,TYPE,MONEY,PATIENT_ACCOUNT) values (null,32,'2019-12-12 0:39:52',' 咨询支出','条否','支出',100,'123');
Insert into JX190718.BUYRECORD (FEIFEN,ID,MONEYTIME,MATTER,KEY_PERSON,TYPE,MONEY,PATIENT_ACCOUNT) values (null,33,'2019-12-12 0:39:54',' 咨询支出','条否','支出',100,'123');
Insert into JX190718.BUYRECORD (FEIFEN,ID,MONEYTIME,MATTER,KEY_PERSON,TYPE,MONEY,PATIENT_ACCOUNT) values (null,36,'2019-12-12 0:54:41',' 咨询支出','条否','支出',100,'123');
Insert into JX190718.BUYRECORD (FEIFEN,ID,MONEYTIME,MATTER,KEY_PERSON,TYPE,MONEY,PATIENT_ACCOUNT) values (null,37,'2019-12-12 0:54:43',' 咨询支出','条否','支出',100,'123');
Insert into JX190718.BUYRECORD (FEIFEN,ID,MONEYTIME,MATTER,KEY_PERSON,TYPE,MONEY,PATIENT_ACCOUNT) values (null,52,'2019-12-13 22:53:48','评测支出','系统','支出',100,'123');
Insert into JX190718.BUYRECORD (FEIFEN,ID,MONEYTIME,MATTER,KEY_PERSON,TYPE,MONEY,PATIENT_ACCOUNT) values (null,34,'2019-12-12 0:40:21',' 咨询支出','条否','支出',100,'123');
Insert into JX190718.BUYRECORD (FEIFEN,ID,MONEYTIME,MATTER,KEY_PERSON,TYPE,MONEY,PATIENT_ACCOUNT) values (null,35,'2019-12-12 0:54:39',' 咨询支出','条否','支出',100,'123');
Insert into JX190718.BUYRECORD (FEIFEN,ID,MONEYTIME,MATTER,KEY_PERSON,TYPE,MONEY,PATIENT_ACCOUNT) values (null,61,'2019-12-16 9:27:57','评测支出','系统','支出',100,'123');
Insert into JX190718.BUYRECORD (FEIFEN,ID,MONEYTIME,MATTER,KEY_PERSON,TYPE,MONEY,PATIENT_ACCOUNT) values (null,41,'2019-12-12 15:01:38','充值','用户','收入',100,'123');
Insert into JX190718.BUYRECORD (FEIFEN,ID,MONEYTIME,MATTER,KEY_PERSON,TYPE,MONEY,PATIENT_ACCOUNT) values (null,42,'2019-12-12 15:10:24','充值','用户','收入',200,'123');
Insert into JX190718.BUYRECORD (FEIFEN,ID,MONEYTIME,MATTER,KEY_PERSON,TYPE,MONEY,PATIENT_ACCOUNT) values (null,51,'2019-12-13 22:51:34','评测支出','系统','支出',100,'123');
REM INSERTING into JX190718.DIAGNOSTIC
SET DEFINE OFF;
Insert into JX190718.DIAGNOSTIC (ID,PROBLEM_ID,REPLY,REPLY_TIME,APPRAISE) values (null,373,'58588','2019-12-12 0:40:00','null');
Insert into JX190718.DIAGNOSTIC (ID,PROBLEM_ID,REPLY,REPLY_TIME,APPRAISE) values (null,372,'8587587285875','2019-12-12 0:40:06','null');
Insert into JX190718.DIAGNOSTIC (ID,PROBLEM_ID,REPLY,REPLY_TIME,APPRAISE) values (null,378,'null','null','null');
Insert into JX190718.DIAGNOSTIC (ID,PROBLEM_ID,REPLY,REPLY_TIME,APPRAISE) values (null,380,'3132','2019-12-11 20:43:07','213123');
Insert into JX190718.DIAGNOSTIC (ID,PROBLEM_ID,REPLY,REPLY_TIME,APPRAISE) values (null,377,'null','null','null');
Insert into JX190718.DIAGNOSTIC (ID,PROBLEM_ID,REPLY,REPLY_TIME,APPRAISE) values (null,382,'null','null','null');
Insert into JX190718.DIAGNOSTIC (ID,PROBLEM_ID,REPLY,REPLY_TIME,APPRAISE) values (null,371,'null','null','null');
Insert into JX190718.DIAGNOSTIC (ID,PROBLEM_ID,REPLY,REPLY_TIME,APPRAISE) values (null,374,'null','null','null');
Insert into JX190718.DIAGNOSTIC (ID,PROBLEM_ID,REPLY,REPLY_TIME,APPRAISE) values (null,395,'null','null','null');
Insert into JX190718.DIAGNOSTIC (ID,PROBLEM_ID,REPLY,REPLY_TIME,APPRAISE) values (null,411,'null','null','null');
Insert into JX190718.DIAGNOSTIC (ID,PROBLEM_ID,REPLY,REPLY_TIME,APPRAISE) values (null,379,'null','null','null');
REM INSERTING into JX190718.MENU
SET DEFINE OFF;
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,2,null,'业务管理','#');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,3,null,'统计报表','#');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,4,null,'系统管理','#');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,5,1,'客户管理','/PsychologicalConsultationPlatform/MyMenuServlet?methodName=userManagement');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,6,1,'后台用户管理','/PsychologicalConsultationPlatform/MyMenuServlet?methodName=backuserManagement');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,7,1,'资金账户','/PsychologicalConsultationPlatform/MyMenuServlet?methodName=staffMoneyRecord');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,8,2,'预约时间设置 ','/PsychologicalConsultationPlatform/MyMenuServlet?methodName=appointment');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,9,2,'预约诊断','/PsychologicalConsultationPlatform/MyMenuServlet?methodName=appointmentManagement');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,10,2,'咨询管理','/PsychologicalConsultationPlatform/MyMenuServlet?methodName=backAppointment');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,11,2,'培训管理','#');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,12,2,'在线评估管理','/PsychologicalConsultationPlatform/MyMenuServlet?methodName=myReportliset');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,13,2,'资格认证管理','#');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,14,3,'用户统计','/PsychologicalConsultationPlatform/MyMenuServlet?methodName=userCount');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,15,3,'渠道量统计','/PsychologicalConsultationPlatform/MyMenuServlet?methodName=channelCount');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,16,4,'菜单管理','#');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,17,4,'角色管理','#');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,18,4,'权限管理','/PsychologicalConsultationPlatform/MyMenuServlet?methodName=menuList');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,19,4,'日志查看','#');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,20,4,'参数配置','#');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,1,null,'账户管理','#');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,21,null,'我要预约','/PsychologicalConsultationPlatform/MyMenuServlet?methodName=userAppointment');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,22,null,'我的报告','/PsychologicalConsultationPlatform/MyMenuServlet?methodName=myReport');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,23,null,'在线评估','/PsychologicalConsultationPlatform/MyMenuServlet?methodName=assess');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,24,null,'咨询师库','#');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,25,null,'我的账户','/PsychologicalConsultationPlatform/MyMenuServlet?methodName=mypurse');
Insert into JX190718.MENU (FEIFEN,MENU_ID,FARTHER_ID,MENU_NAME,MENU_PATH) values (null,26,2,'题库管理','/PsychologicalConsultationPlatform/MyMenuServlet?methodName=mySubject');
REM INSERTING into JX190718.PATIENT
SET DEFINE OFF;
Insert into JX190718.PATIENT (PATIENT_ID,ROLE_ID,PATIENT_ACCOUNT,PATIENT_NAME,PATIENT_PWD,PATIENT_SEXY,PATIENT_AGE,PATIENT_STAGE,PATIENT_REGTIME,PHONE,PURSE) values (29,2,'123','洪均','123456','0',18,'1','2019-12-30 9:44:20',13550564614,300);
Insert into JX190718.PATIENT (PATIENT_ID,ROLE_ID,PATIENT_ACCOUNT,PATIENT_NAME,PATIENT_PWD,PATIENT_SEXY,PATIENT_AGE,PATIENT_STAGE,PATIENT_REGTIME,PHONE,PURSE) values (49,2,'1235','洪天','111111','1',17,'2','2019-08-29 13:26:14',13525645455,null);
Insert into JX190718.PATIENT (PATIENT_ID,ROLE_ID,PATIENT_ACCOUNT,PATIENT_NAME,PATIENT_PWD,PATIENT_SEXY,PATIENT_AGE,PATIENT_STAGE,PATIENT_REGTIME,PHONE,PURSE) values (38,2,'156','洪洪','111111','0',18,'2','2019-12-29 10:06:16',13512334155,null);
Insert into JX190718.PATIENT (PATIENT_ID,ROLE_ID,PATIENT_ACCOUNT,PATIENT_NAME,PATIENT_PWD,PATIENT_SEXY,PATIENT_AGE,PATIENT_STAGE,PATIENT_REGTIME,PHONE,PURSE) values (40,2,'145','洪俊','111111','1',18,'2','2019-12-09 10:18:25',13543535154,null);
Insert into JX190718.PATIENT (PATIENT_ID,ROLE_ID,PATIENT_ACCOUNT,PATIENT_NAME,PATIENT_PWD,PATIENT_SEXY,PATIENT_AGE,PATIENT_STAGE,PATIENT_REGTIME,PHONE,PURSE) values (41,2,'1454','洪俊','111111','0',18,'2','2019-12-15 10:19:16',13543535154,null);
Insert into JX190718.PATIENT (PATIENT_ID,ROLE_ID,PATIENT_ACCOUNT,PATIENT_NAME,PATIENT_PWD,PATIENT_SEXY,PATIENT_AGE,PATIENT_STAGE,PATIENT_REGTIME,PHONE,PURSE) values (42,2,'14545','洪俊','111111','0',18,'2','2019-12-21 10:20:01',13543535154,null);
Insert into JX190718.PATIENT (PATIENT_ID,ROLE_ID,PATIENT_ACCOUNT,PATIENT_NAME,PATIENT_PWD,PATIENT_SEXY,PATIENT_AGE,PATIENT_STAGE,PATIENT_REGTIME,PHONE,PURSE) values (45,2,'1561321543','洪俊新','111111','1',18,'1','2019-12-03 10:25:09',18751864475,null);
Insert into JX190718.PATIENT (PATIENT_ID,ROLE_ID,PATIENT_ACCOUNT,PATIENT_NAME,PATIENT_PWD,PATIENT_SEXY,PATIENT_AGE,PATIENT_STAGE,PATIENT_REGTIME,PHONE,PURSE) values (46,2,'15613215436','洪俊新','111111','0',18,'2','2019-12-01 10:26:33',18751864475,null);
Insert into JX190718.PATIENT (PATIENT_ID,ROLE_ID,PATIENT_ACCOUNT,PATIENT_NAME,PATIENT_PWD,PATIENT_SEXY,PATIENT_AGE,PATIENT_STAGE,PATIENT_REGTIME,PHONE,PURSE) values (47,2,'1534531234','洪俊','111111','1',18,'1','2019-12-12 10:56:09',18243345643,null);
Insert into JX190718.PATIENT (PATIENT_ID,ROLE_ID,PATIENT_ACCOUNT,PATIENT_NAME,PATIENT_PWD,PATIENT_SEXY,PATIENT_AGE,PATIENT_STAGE,PATIENT_REGTIME,PHONE,PURSE) values (9,2,'123456','洪洪','1111111','1',12,'1','2019-12-27 10:20:01',13456431346,null);
Insert into JX190718.PATIENT (PATIENT_ID,ROLE_ID,PATIENT_ACCOUNT,PATIENT_NAME,PATIENT_PWD,PATIENT_SEXY,PATIENT_AGE,PATIENT_STAGE,PATIENT_REGTIME,PHONE,PURSE) values (19,2,'1234','洪局','11111','0',15,'3','2019-12-11 10:20:01',13651235421,null);
Insert into JX190718.PATIENT (PATIENT_ID,ROLE_ID,PATIENT_ACCOUNT,PATIENT_NAME,PATIENT_PWD,PATIENT_SEXY,PATIENT_AGE,PATIENT_STAGE,PATIENT_REGTIME,PHONE,PURSE) values (20,2,'12345','洪局','111111','0',15,'2','2019-12-11 10:15:01',13651235421,null);
REM INSERTING into JX190718.REPORT_TABLE
SET DEFINE OFF;
Insert into JX190718.REPORT_TABLE (RESULT,REPORT_ID,PATIENT_ACCOUNT,REPORT_TIME,SUBJECT_DOMAIN,SCORE,RESULT_TEXT) values ('家庭关系良好',5,'123','2019-12-15','家庭关系','11        ','xxxxxxxxxxxxx');
Insert into JX190718.REPORT_TABLE (RESULT,REPORT_ID,PATIENT_ACCOUNT,REPORT_TIME,SUBJECT_DOMAIN,SCORE,RESULT_TEXT) values ('家庭关系一般',7,'123','2019-12-12','家庭关系','8         ','xxxxxxxxxxxxx');
Insert into JX190718.REPORT_TABLE (RESULT,REPORT_ID,PATIENT_ACCOUNT,REPORT_TIME,SUBJECT_DOMAIN,SCORE,RESULT_TEXT) values ('家庭关系良好',9,'123','2019-12-13','家庭关系','9         ','xxxxxxxxxxxxx');
Insert into JX190718.REPORT_TABLE (RESULT,REPORT_ID,PATIENT_ACCOUNT,REPORT_TIME,SUBJECT_DOMAIN,SCORE,RESULT_TEXT) values ('教育优秀',12,'123','2019-12-13','教育心理学','13        ','xxxxxxxxxxxxx');
Insert into JX190718.REPORT_TABLE (RESULT,REPORT_ID,PATIENT_ACCOUNT,REPORT_TIME,SUBJECT_DOMAIN,SCORE,RESULT_TEXT) values ('教育优秀',23,'123','2019-12-13','教育心理学','14        ','xxxxxxxxxxxxx');
Insert into JX190718.REPORT_TABLE (RESULT,REPORT_ID,PATIENT_ACCOUNT,REPORT_TIME,SUBJECT_DOMAIN,SCORE,RESULT_TEXT) values ('家庭关系优秀',3,'123','2019-12-04','家庭关系','18        ','xxxxxxxxxxxxx');
Insert into JX190718.REPORT_TABLE (RESULT,REPORT_ID,PATIENT_ACCOUNT,REPORT_TIME,SUBJECT_DOMAIN,SCORE,RESULT_TEXT) values ('家庭关系一般',31,'123','2019-12-16','家庭关系','7         ','xxxxxxxxxxxxx');
Insert into JX190718.REPORT_TABLE (RESULT,REPORT_ID,PATIENT_ACCOUNT,REPORT_TIME,SUBJECT_DOMAIN,SCORE,RESULT_TEXT) values ('家庭关系良好',8,'123','2019-12-16','家庭关系','12        ','xxxxxxxxxxxxx');
Insert into JX190718.REPORT_TABLE (RESULT,REPORT_ID,PATIENT_ACCOUNT,REPORT_TIME,SUBJECT_DOMAIN,SCORE,RESULT_TEXT) values ('家庭关系良好',4,'123','2019-12-18','家庭关系','11        ','xxxxxxxxxxxxx');
Insert into JX190718.REPORT_TABLE (RESULT,REPORT_ID,PATIENT_ACCOUNT,REPORT_TIME,SUBJECT_DOMAIN,SCORE,RESULT_TEXT) values ('家庭关系良好',6,'123','2019-12-19','家庭关系','10        ','xxxxxxxxxxxxx');
Insert into JX190718.REPORT_TABLE (RESULT,REPORT_ID,PATIENT_ACCOUNT,REPORT_TIME,SUBJECT_DOMAIN,SCORE,RESULT_TEXT) values ('教育优秀',10,'123','2019-12-13','教育心理学','13        ','xxxxxxxxxxxxx');
Insert into JX190718.REPORT_TABLE (RESULT,REPORT_ID,PATIENT_ACCOUNT,REPORT_TIME,SUBJECT_DOMAIN,SCORE,RESULT_TEXT) values ('运动良好',11,'123','2019-12-13','运动心理学','9         ','xxxxxxxxxxxxx');
Insert into JX190718.REPORT_TABLE (RESULT,REPORT_ID,PATIENT_ACCOUNT,REPORT_TIME,SUBJECT_DOMAIN,SCORE,RESULT_TEXT) values ('家庭关系优秀',21,'123','2019-12-13','家庭关系','15        ','xxxxxxxxxxxxx');
Insert into JX190718.REPORT_TABLE (RESULT,REPORT_ID,PATIENT_ACCOUNT,REPORT_TIME,SUBJECT_DOMAIN,SCORE,RESULT_TEXT) values ('家庭关系优秀',22,'123','2019-12-13','家庭关系','13        ','xxxxxxxxxxxxx');
Insert into JX190718.REPORT_TABLE (RESULT,REPORT_ID,PATIENT_ACCOUNT,REPORT_TIME,SUBJECT_DOMAIN,SCORE,RESULT_TEXT) values ('运动良好',24,'123','2019-12-13','运动心理学','12        ','xxxxxxxxxxxxx');
REM INSERTING into JX190718.ROLE
SET DEFINE OFF;
Insert into JX190718.ROLE (FEIFEN,ROLE_ID,ROLE_NAME) values (null,2,'用户');
Insert into JX190718.ROLE (FEIFEN,ROLE_ID,ROLE_NAME) values (null,0,'系统管理员');
Insert into JX190718.ROLE (FEIFEN,ROLE_ID,ROLE_NAME) values (null,1,'咨询师');
REM INSERTING into JX190718.ROLE_MENU
SET DEFINE OFF;
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,19,'咨询师',8,'可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,20,'咨询师',9,'可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,21,'系统管理员',5,'可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,23,'系统管理员',6,'可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,24,'系统管理员',10,'可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,25,'系统管理员',11,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,26,'系统管理员',12,'可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,27,'系统管理员',13,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,28,'系统管理员',14,'可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,29,'系统管理员',15,'可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,30,'系统管理员',16,'可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,31,'系统管理员',17,'可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,32,'系统管理员',18,'可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,33,'系统管理员',19,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,34,'系统管理员',20,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,46,'用户',21,'可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,47,'用户',22,'可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,48,'用户',23,'可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,49,'用户',24,'可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,50,'用户',25,'可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,1,'咨询师',7,'可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,51,'系统管理员',26,'可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,61,'系统管理员',7,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,62,'系统管理员',8,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,63,'系统管理员',9,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,75,'咨询师',20,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,76,'咨询师',19,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,77,'咨询师',17,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,78,'咨询师',5,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,79,'咨询师',6,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,80,'咨询师',10,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,81,'咨询师',11,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,82,'咨询师',12,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,83,'咨询师',13,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,84,'咨询师',14,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,74,'咨询师',26,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,85,'咨询师',15,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,86,'咨询师',16,'不可用');
Insert into JX190718.ROLE_MENU (FEIFEN,ID,ROLE_NAME,MENU_ID,MENU_STAGE) values (null,87,'咨询师',18,'不可用');
REM INSERTING into JX190718.SCHEDULING
SET DEFINE OFF;
Insert into JX190718.SCHEDULING (STAFF_NAME,SCHEDULING_ID,STAFF_ACCOUNT,DATADAY) values ('条否',181,'159','2019-12-12');
Insert into JX190718.SCHEDULING (STAFF_NAME,SCHEDULING_ID,STAFF_ACCOUNT,DATADAY) values ('dsadqw',201,'123124','2019-12-16');
Insert into JX190718.SCHEDULING (STAFF_NAME,SCHEDULING_ID,STAFF_ACCOUNT,DATADAY) values ('dwad',203,'123456','2019-12-16');
Insert into JX190718.SCHEDULING (STAFF_NAME,SCHEDULING_ID,STAFF_ACCOUNT,DATADAY) values ('条否',182,'159','2019-12-13');
Insert into JX190718.SCHEDULING (STAFF_NAME,SCHEDULING_ID,STAFF_ACCOUNT,DATADAY) values ('条否',183,'159','2019-12-14');
Insert into JX190718.SCHEDULING (STAFF_NAME,SCHEDULING_ID,STAFF_ACCOUNT,DATADAY) values ('dsadqw',202,'123124','2019-12-17');
Insert into JX190718.SCHEDULING (STAFF_NAME,SCHEDULING_ID,STAFF_ACCOUNT,DATADAY) values ('dwad',204,'123456','2019-12-17');
REM INSERTING into JX190718.STAFF
SET DEFINE OFF;
Insert into JX190718.STAFF (FEIFEN,STAFF_STAGE,STAFF_ID,STAFF_ACCOUNT,ROLE_ID,STAFF_NAME,STAFF_SEXY,STAFF_PWD,STAFF_SCHOOL,STAFF_AWARDED,STAFF_DOMAIN,STAFF_BACKGROUND,STAFF_RESUME,COST,PURSE) values (null,null,1,'1234',0,'好好啊','女','1234',null,null,null,null,null,null,null);
Insert into JX190718.STAFF (FEIFEN,STAFF_STAGE,STAFF_ID,STAFF_ACCOUNT,ROLE_ID,STAFF_NAME,STAFF_SEXY,STAFF_PWD,STAFF_SCHOOL,STAFF_AWARDED,STAFF_DOMAIN,STAFF_BACKGROUND,STAFF_RESUME,COST,PURSE) values (null,1,2,'123',1,'得分','男','123456','三国大学','教授','亲子关系','xxx                                               ','xxx',100,null);
Insert into JX190718.STAFF (FEIFEN,STAFF_STAGE,STAFF_ID,STAFF_ACCOUNT,ROLE_ID,STAFF_NAME,STAFF_SEXY,STAFF_PWD,STAFF_SCHOOL,STAFF_AWARDED,STAFF_DOMAIN,STAFF_BACKGROUND,STAFF_RESUME,COST,PURSE) values (null,1,33,'123124',1,'dsadqw','0','123124','feqweq','教授','教育心理学','xsxxxxxxxxxxxx                                    ','xxxxxxxxxxxxxxx',200,null);
Insert into JX190718.STAFF (FEIFEN,STAFF_STAGE,STAFF_ID,STAFF_ACCOUNT,ROLE_ID,STAFF_NAME,STAFF_SEXY,STAFF_PWD,STAFF_SCHOOL,STAFF_AWARDED,STAFF_DOMAIN,STAFF_BACKGROUND,STAFF_RESUME,COST,PURSE) values (null,1,32,'123456',1,'dwad','1','123456','sdfsdfa','教授','运动心理学','xxxxxxxx                                          ','xxxxxxx',200,null);
Insert into JX190718.STAFF (FEIFEN,STAFF_STAGE,STAFF_ID,STAFF_ACCOUNT,ROLE_ID,STAFF_NAME,STAFF_SEXY,STAFF_PWD,STAFF_SCHOOL,STAFF_AWARDED,STAFF_DOMAIN,STAFF_BACKGROUND,STAFF_RESUME,COST,PURSE) values (null,2,21,'12312',0,'WEWQ','0','123456','AWEWQE','副教授',null,null,null,null,null);
Insert into JX190718.STAFF (FEIFEN,STAFF_STAGE,STAFF_ID,STAFF_ACCOUNT,ROLE_ID,STAFF_NAME,STAFF_SEXY,STAFF_PWD,STAFF_SCHOOL,STAFF_AWARDED,STAFF_DOMAIN,STAFF_BACKGROUND,STAFF_RESUME,COST,PURSE) values (null,1,22,'12345',0,'WRWE','0','123456','QWEQW','副教授',null,null,null,null,null);
Insert into JX190718.STAFF (FEIFEN,STAFF_STAGE,STAFF_ID,STAFF_ACCOUNT,ROLE_ID,STAFF_NAME,STAFF_SEXY,STAFF_PWD,STAFF_SCHOOL,STAFF_AWARDED,STAFF_DOMAIN,STAFF_BACKGROUND,STAFF_RESUME,COST,PURSE) values (null,3,23,'23124',0,'adfaf','0','123456','sdfsf','讲师',null,null,null,null,null);
Insert into JX190718.STAFF (FEIFEN,STAFF_STAGE,STAFF_ID,STAFF_ACCOUNT,ROLE_ID,STAFF_NAME,STAFF_SEXY,STAFF_PWD,STAFF_SCHOOL,STAFF_AWARDED,STAFF_DOMAIN,STAFF_BACKGROUND,STAFF_RESUME,COST,PURSE) values (null,1,24,'159',1,'条否','0','123456','dfef','教授','家庭关系','xxxxx                                             ','xxxxx',100,700);
REM INSERTING into JX190718.SUBJECT
SET DEFINE OFF;
Insert into JX190718.SUBJECT (FEIFEN,SUBJECT_ID,SUBJECT_TEXT,SUBJECT_DOMAIN,OPTION_A,OPTION_B,OPTION_C,OPTION_D) values (null,8,'在你面前有一对可爱的双胞胎，如果你是他们的父母，你会为他们穿戴哪一种不同的衣饰来辨认他们呢？','运动心理学','不同颜色的帽子','不同款式的奶嘴','不同颜色的衣服','不同颜色的鞋子');
Insert into JX190718.SUBJECT (FEIFEN,SUBJECT_ID,SUBJECT_TEXT,SUBJECT_DOMAIN,OPTION_A,OPTION_B,OPTION_C,OPTION_D) values (null,9,'你想吃那个呢？','运动心理学','奶油螃蟹','清蒸螃蟹','咖喱螃蟹','螃蟹高汤');
Insert into JX190718.SUBJECT (FEIFEN,SUBJECT_ID,SUBJECT_TEXT,SUBJECT_DOMAIN,OPTION_A,OPTION_B,OPTION_C,OPTION_D) values (null,10,'最近大家都流行将透明的玻璃瓶里面放置彩色的珠子，请凭着你的直觉，挑选你自己喜欢的珠子颜色。','运动心理学','红色','蓝色','白色','透明');
Insert into JX190718.SUBJECT (FEIFEN,SUBJECT_ID,SUBJECT_TEXT,SUBJECT_DOMAIN,OPTION_A,OPTION_B,OPTION_C,OPTION_D) values (null,11,'你认为西方魔鬼的图腾中，最有力量的象征是','教育心理学','头上的角','手上拿的魔鬼叉子','锐利的牙齿','结实纠结的肌肉');
Insert into JX190718.SUBJECT (FEIFEN,SUBJECT_ID,SUBJECT_TEXT,SUBJECT_DOMAIN,OPTION_A,OPTION_B,OPTION_C,OPTION_D) values (null,7,'请直接凭着你的直觉来选择，黄牛、水牛、乳牛，哪一种牛对人类的贡献最大。','运动心理学','黄牛','水牛','乳牛','海牛');
Insert into JX190718.SUBJECT (FEIFEN,SUBJECT_ID,SUBJECT_TEXT,SUBJECT_DOMAIN,OPTION_A,OPTION_B,OPTION_C,OPTION_D) values (null,12,'你是怎样看待蜘蛛侠、超人等这类英雄的？','教育心理学','很崇拜他们','很同情他们','无感','很羡慕他们');
Insert into JX190718.SUBJECT (FEIFEN,SUBJECT_ID,SUBJECT_TEXT,SUBJECT_DOMAIN,OPTION_A,OPTION_B,OPTION_C,OPTION_D) values (null,13,'睡前，你认为下面哪件事是比较不可能省略的？','教育心理学','泡脚','玩手机','看书','幻想');
Insert into JX190718.SUBJECT (FEIFEN,SUBJECT_ID,SUBJECT_TEXT,SUBJECT_DOMAIN,OPTION_A,OPTION_B,OPTION_C,OPTION_D) values (null,14,'跟同事一起吃饭，你会扮演哪种角色？','教育心理学','滔滔不绝的话痨','闷声不响的呆瓜','大吃大喝的吃货','体贴热情的照顾者');
Insert into JX190718.SUBJECT (FEIFEN,SUBJECT_ID,SUBJECT_TEXT,SUBJECT_DOMAIN,OPTION_A,OPTION_B,OPTION_C,OPTION_D) values (null,15,'念书时，最令你感到开心的事是：','教育心理学','每天什么都不用担心，只用读书','可以跟同学无忧无虑地打闹','可以谈一场单纯的恋爱','能够得到真诚的友谊');
Insert into JX190718.SUBJECT (FEIFEN,SUBJECT_ID,SUBJECT_TEXT,SUBJECT_DOMAIN,OPTION_A,OPTION_B,OPTION_C,OPTION_D) values (null,16,'你的衣服一般怎么摆放的？','教育心理学','衣服按款式类型分类摆放','衣服按季节分类摆放','衣服乱放','衣服按颜色分类摆放');
Insert into JX190718.SUBJECT (FEIFEN,SUBJECT_ID,SUBJECT_TEXT,SUBJECT_DOMAIN,OPTION_A,OPTION_B,OPTION_C,OPTION_D) values (null,17,'你认为每天不可缺少的食物是：','家庭关系','主食','肉类','肉类','无所谓，喜欢的不能少就行');
Insert into JX190718.SUBJECT (FEIFEN,SUBJECT_ID,SUBJECT_TEXT,SUBJECT_DOMAIN,OPTION_A,OPTION_B,OPTION_C,OPTION_D) values (null,18,'你更喜欢花大价钱买哪类衣服？','家庭关系','鞋子','大衣','贴身衣物','包包');
Insert into JX190718.SUBJECT (FEIFEN,SUBJECT_ID,SUBJECT_TEXT,SUBJECT_DOMAIN,OPTION_A,OPTION_B,OPTION_C,OPTION_D) values (null,19,'你更在意哪种家居产品？','家庭关系','床上用品','餐具','沙发巾','浴巾、毛巾');
Insert into JX190718.SUBJECT (FEIFEN,SUBJECT_ID,SUBJECT_TEXT,SUBJECT_DOMAIN,OPTION_A,OPTION_B,OPTION_C,OPTION_D) values (null,20,'发生下面哪件事，会让你最心痛？','家庭关系','遭到朋友背叛','被父母看不起','受到恋人的欺骗','被信任的同事出卖');
Insert into JX190718.SUBJECT (FEIFEN,SUBJECT_ID,SUBJECT_TEXT,SUBJECT_DOMAIN,OPTION_A,OPTION_B,OPTION_C,OPTION_D) values (null,21,'下面哪件事会让你感到最自责？','家庭关系','忘记了妈妈的生日','因为自己的任性害得恋人失业了','不小心把同事的电脑弄坏了 ','无意中破坏了朋友的恋情');
Insert into JX190718.SUBJECT (FEIFEN,SUBJECT_ID,SUBJECT_TEXT,SUBJECT_DOMAIN,OPTION_A,OPTION_B,OPTION_C,OPTION_D) values (null,22,'到餐厅吃饭的时候你会选择','家庭关系','点熟悉的饭菜','点新奇的饭菜','点优惠的饭菜','无固定的点法');
Insert into JX190718.SUBJECT (FEIFEN,SUBJECT_ID,SUBJECT_TEXT,SUBJECT_DOMAIN,OPTION_A,OPTION_B,OPTION_C,OPTION_D) values (null,31,'在你准备进电梯时,它刚好升了上去,你只差那么一小步。没办法,只好等下一趟了。在等待的过程中,你通常会做什么呢?','运动心理学','一直盯着电梯的按钮,并且按了好几次。','双脚踏来踏去,不停地发出声响。','朝上看,或是看周围的告示板。','向下看。');
--------------------------------------------------------
--  DDL for Index PATIENT_ACCOUNT
--------------------------------------------------------

  CREATE UNIQUE INDEX "JX190718"."PATIENT_ACCOUNT" ON "JX190718"."PATIENT" ("PATIENT_ACCOUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MENU
--------------------------------------------------------

  CREATE UNIQUE INDEX "JX190718"."PK_MENU" ON "JX190718"."MENU" ("MENU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLE_MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JX190718"."ROLE_MENU_PK" ON "JX190718"."ROLE_MENU" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STAFF_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "JX190718"."STAFF_UK1" ON "JX190718"."STAFF" ("STAFF_ACCOUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SCHEDULING
--------------------------------------------------------

  CREATE UNIQUE INDEX "JX190718"."PK_SCHEDULING" ON "JX190718"."SCHEDULING" ("SCHEDULING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ROLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "JX190718"."PK_ROLE" ON "JX190718"."ROLE" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PATIENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "JX190718"."PK_PATIENT" ON "JX190718"."PATIENT" ("PATIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_STAFF
--------------------------------------------------------

  CREATE UNIQUE INDEX "JX190718"."PK_STAFF" ON "JX190718"."STAFF" ("STAFF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_REPORT_TABLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "JX190718"."PK_REPORT_TABLE" ON "JX190718"."REPORT_TABLE" ("REPORT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SUBJECT
--------------------------------------------------------

  CREATE UNIQUE INDEX "JX190718"."PK_SUBJECT" ON "JX190718"."SUBJECT" ("SUBJECT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index APPOINTMENT_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "JX190718"."APPOINTMENT_UK1" ON "JX190718"."APPOINTMENT" ("PROBLEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BUYRECORD
--------------------------------------------------------

  CREATE UNIQUE INDEX "JX190718"."PK_BUYRECORD" ON "JX190718"."BUYRECORD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  
  
--------------------------------------------------------
--  DDL for Trigger TIB_APPOINTMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "JX190718"."TIB_APPOINTMENT" before insert
on "JX190718".APPOINTMENT for each row
begin
    --  Column "PROBLEM_ID" uses sequence APPOINTMENT_SEQ
    select "JX190718".APPOINTMENT_SEQ.NEXTVAL INTO :new.PROBLEM_ID from dual;
end;
/
--------------------------------------------------------
--  DDL for Trigger TIB_BUYRECORD
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "JX190718"."TIB_BUYRECORD" before insert
on "JX190718".BUYRECORD for each row
begin
    --  Column "ID" uses sequence BUYRECORD_SEQ
    select "JX190718".BUYRECORD_SEQ.NEXTVAL INTO :new.ID from dual;
end;

/
--------------------------------------------------------
--  DDL for Trigger TIB_PATIENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "JX190718"."TIB_PATIENT" before insert
on "JX190718".PATIENT for each row
begin
    --  Column "PATIENT_ID" uses sequence PATIENT_ID_SEQ
    select "JX190718".PATIENT_ID_SEQ.NEXTVAL INTO :new.PATIENT_ID from dual;
end;

/
--------------------------------------------------------
--  DDL for Trigger TIB_REPORT_TABLE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "JX190718"."TIB_REPORT_TABLE" before insert
on "JX190718".REPORT_TABLE for each row
begin
    --  Column "REPORT_ID" uses sequence REPORT_SEQ
    select "JX190718".REPORT_SEQ.NEXTVAL INTO :new.REPORT_ID from dual;
end;

/
--------------------------------------------------------
--  DDL for Trigger TIB_ROLE_MENU
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "JX190718"."TIB_ROLE_MENU" before insert
on "JX190718".ROLE_MENU for each row
begin
    --  Column "ID" uses sequence ROLE_MENU_SEQ
    select "JX190718".ROLE_MENU_SEQ.NEXTVAL INTO :new.ID from dual;
end;

/
--------------------------------------------------------
--  DDL for Trigger TIB_SCHEDULING
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "JX190718"."TIB_SCHEDULING" before insert
on "JX190718".SCHEDULING for each row
begin
    --  Column "SCHEDULING_ID" uses sequence SCHEDULING_SEQ
    select "JX190718".SCHEDULING_SEQ.NEXTVAL INTO :new.SCHEDULING_ID from dual;
end;
/
--------------------------------------------------------
--  DDL for Trigger TIB_STAFF
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "JX190718"."TIB_STAFF" before insert
on "JX190718".STAFF for each row
begin
    --  Column "STAFF_ID" uses sequence STAFF_ID_SEQ
    select "JX190718".STAFF_ID_SEQ.NEXTVAL INTO :new.STAFF_ID from dual;
end;

/
--------------------------------------------------------
--  DDL for Trigger TIB_SUBJECT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "JX190718"."TIB_SUBJECT" before insert
on "JX190718".SUBJECT for each row
begin
    --  Column "SUBJECT_ID" uses sequence SUBJECT_ID_SEQ
    select "JX190718".SUBJECT_ID_SEQ.NEXTVAL INTO :new.SUBJECT_ID from dual;
end;
/
